### ISSUE TITLE
make use of google iot-device-sdk-embedded-c

### ISSUE THREAD

**Issue by mcallistertad** [mcallistertad/nrf_google_iot_core#3]
**Issue**
For better portability and reliability, use of this sdk would be preferable to the current library.

**Solution**
Fork and port iot-device-sdk-embedded-c to ZephyrOS.

**Alternatives**
Update current gcp-iot lib.

**Context**
https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/

**Comment by JeffreyUrban** [comment]
I was considering this as well, but think it might be the wrong way about it.

The [Google IoT Core Embedded C SDK](https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/) appears to provide similar foundations as Zephyr does natively (rather than much in terms of management on top of them), so the Google IoT Core Embedded C SDK appears redundant, and it may be better to rely more on Zephyr’s native support, except to the extent there is anything that really is specific to Google Cloud IoT Core. 

The Google IoT Core Embedded C SDK appears to make more sense for more bare bones RTOS without much of a native networking stack.

**Comment by JeffreyUrban** [comment]
As an alternative solution, I adapted the Zephyr [google_iot_mqtt example](https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/net/cloud/google_iot_mqtt) to work on my nRF9160-DK dev kit with nRF Connect SDK v1.71. and modem firmware v1.31. See [the repo](https://github.com/JeffreyUrban/nRF9160-google_iot_mqtt). Instructions are in the README.rst.

**Comment by mcallistertad** [comment]
@JeffreyUrban you're on the right track with this. It makes more sense to rely on Zephyr's networking stack.
